### ISSUE TITLE
Snapshot dependencies not found

### ISSUE THREAD

**Issue by dirri** [BraintagsGmbH/NetRelay-Demoproject#1]
I tried to build the demo project but it failed to find SNAPSHOT deps as referred in pom.
Then i added the repo https://oss.sonatype.org/content/repositories/snapshots and the build now starts but fails a minute later again trying to fetch httpmime sources : Could not find artifact org.apache.httpcomponents:httpmime:jar:sources:4.4-alpha2-SNAPSHOT
Which repos do i need to add to get that build done?

thx alot!

**Comment by remi128** [comment]
sorry for the late reply, was in my annual hollidays.
httpmime was an old reference, which i just removed inside the current snapshot of NetRelay. Additionally i just added some missing files into the webroot of the NetRelay-DemoProject.

**Comment by remi128** [comment]
Please update dependencies to:
- <parent>
-  <groupId>de.braintags</groupId>
-  <artifactId>btVertxBasePOM</artifactId>
-  <version>19-SNAPSHOT</version> ( check for the latest version )
- </parent>
- ----
  *
- add properties into the properties section:
- [source,xml,subs="+attributes"]
- ----
- <netrelay.version>10.2.0-SNAPSHOT</netrelay.version> ( check for the latest version )
- <netrelayController.version>1.2.0-SNAPSHOT</netrelayController.version> ( check for the latest version )
- ----

**Comment by dirri** [comment]
fixed
